export const ASSET_STRUCTURAL_TYPES = [
  { value: "assetGroup", label: "Asset Group" },
  { value: "digital", label: "Digital" },
  { value: "digital.audio", label: "Digital - Audio" },
  { value: "digital.audio.object", label: "Digital - Audio Object" },
  { value: "digital.audioVisual", label: "Digital - Audio Visual" },
  { value: "digital.data", label: "Digital - Data" },
  { value: "digital.document", label: "Digital - Document" },
  { value: "digital.image", label: "Digital - Image" },
  { value: "digital.imageSequence", label: "Digital - Image Sequence" },
  { value: "digital.movingImage", label: "Digital - Moving Image" },
  { value: "digital.procedural", label: "Digital - Procedural" },
  { value: "digital.pointCloud", label: "Digital - Point Cloud" },
  { value: "digital.volume", label: "Digital - Volume" },
  { value: "digital.structuredDocument", label: "Digital - Structured Document" },
  { value: "geometry", label: "Geometry" },
  { value: "physical", label: "Physical" },
  { value: "physical.audioVisual", label: "Physical - Audio Visual" },
  { value: "physical.document", label: "Physical - Document" },
  { value: "physical.image", label: "Physical - Image" },
  { value: "physical.imageSequence", label: "Physical - Image Sequence" },
  { value: "physical.movingImage", label: "Physical - Moving Image" },
  { value: "physical.structuredDocument", label: "Physical - Structured Document" }
];

export const ASSET_FUNCTIONAL_TYPES = [
  { value: "artwork", label: "Artwork" },
  { value: "artwork.animatedStoryboard", label: "Artwork - Animated Storyboard" },
  { value: "artwork.conceptArt", label: "Artwork - Concept Art" },
  { value: "artwork.storyboard", label: "Artwork - Storyboard" },
  { value: "artwork.storyboard.frame", label: "Artwork - Storyboard Frame" },
  { value: "audio", label: "Audio" },
  { value: "audio.channel", label: "Audio - Channel" },
  { value: "audio.object", label: "Audio - Object" },
  { value: "audio.objectMetadata", label: "Audio - Object Metadata" },
  { value: "audio.onSetMix", label: "Audio - On Set Mix" },
  { value: "audio.track", label: "Audio - Track" },
  { value: "cameraMetadata", label: "Camera Metadata" },
  { value: "capture", label: "Capture" },
  { value: "capture.audio", label: "Capture - Audio" },
  { value: "capture.audio.wild", label: "Capture - Audio Wild" },
  { value: "capture.calibration", label: "Capture - Calibration" },
  { value: "capture.cameraProxy", label: "Capture - Camera Proxy" },
  { value: "capture.faceCamera", label: "Capture - Face Camera" },
  { value: "capture.lidar", label: "Capture - LIDAR" },
  { value: "capture.motionCapture", label: "Capture - Motion Capture" },
  { value: "capture.ocf", label: "Capture - OCF" },
  { value: "capture.roll", label: "Capture - Roll" },
  { value: "capture.witnessCamera", label: "Capture - Witness Camera" },
  { value: "cgModel", label: "CG Model" },
  { value: "cgPointCloud", label: "CG Point Cloud" },
  { value: "cgRig.biped", label: "CG Rig - Biped" },
  { value: "cgRig.quadruped", label: "CG Rig - Quadruped" },
  { value: "cgRig.polyped", label: "CG Rig - Polyped" },
  { value: "cgRig.avian", label: "CG Rig - Avian" },
  { value: "cgRig.serpentine", label: "CG Rig - Serpentine" },
  { value: "cgRig.appendage", label: "CG Rig - Appendage" },
  { value: "cgVolume", label: "CG Volume" },
  { value: "color", label: "Color" },
  { value: "color.cdl", label: "Color - CDL" },
  { value: "color.colorSpace", label: "Color - Color Space" },
  { value: "color.lut", label: "Color - LUT" },
  { value: "configuration", label: "Configuration" },
  { value: "configuration.colorSpace", label: "Configuration - Color Space" },
  { value: "costume", label: "Costume" },
  { value: "creativeReferenceMaterial", label: "Creative Reference Material" },
  { value: "lensMetadata", label: "Lens Metadata" },
  { value: "map", label: "Map" },
  { value: "material", label: "Material" },
  { value: "material.shader", label: "Material - Shader" },
  { value: "productionCharacter", label: "Production Character" },
  { value: "productionProp", label: "Production Prop" },
  { value: "productionProp.productionGreenery", label: "Production Prop - Greenery" },
  { value: "productionProp.productionVehicle", label: "Production Prop - Vehicle" },
  { value: "productionSetDressing", label: "Production Set Dressing" },
  { value: "productionSetDressing.productionGreenery", label: "Production Set Dressing - Greenery" },
  { value: "productionSetDressing.productionVehicle", label: "Production Set Dressing - Vehicle" },
  { value: "proxy", label: "Proxy" },
  { value: "proxy.daily", label: "Proxy - Daily" },
  { value: "proxy.editorial", label: "Proxy - Editorial" },
  { value: "recorderMetadata", label: "Recorder Metadata" },
  { value: "script", label: "Script" },
  { value: "sequenceChronologyDescriptor", label: "Sequence Chronology Descriptor" },
  { value: "shot", label: "Shot" },
  { value: "shot.animation", label: "Shot - Animation" },
  { value: "shot.editorial", label: "Shot - Editorial" },
  { value: "shot.vfx", label: "Shot - VFX" },
  { value: "technicalReferenceMaterial", label: "Technical Reference Material" },
  { value: "udimTile", label: "UDIM Tile" }
];
