export const ENTITY_TYPES = [
  "CreativeWork",
  "Asset",
  "AssetSC",
  "Character",
  "Collection",
  "Composition",
  "Context",
  "Department",
  "Depiction",
  "Effect",
  "Infrastructure",
  "InfrastructureSC",
  "Location",
  "NarrativeAction",
  "NarrativeAudio",
  "NarrativeLocation",
  "NarrativeObject",
  "NarrativeScene",
  "NarrativeStyling",
  "NarrativeWardrobe",
  "Organization",
  "Participant",
  "Person",
  "ProductionLocation",
  "ProductionScene",
  "Role",
  "Sequence",
  "Service",
  "Slate",
  "SpecialAction",
  "Task",
  "TaskSC"
] as const;

export type EntityType = typeof ENTITY_TYPES[number];
